//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnectivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int clientid { get; set; }
        public string clientname { get; set; }
        public int acctype { get; set; }
        public int money { get; set; }
    }
}
